on:
  [ push, pull_request ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: |
          sudo apt-get update
          sudo apt-get install build-essential procps curl file git
          /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
          echo '# Set PATH, MANPATH, etc., for Homebrew.' >> /home/runner/.bash_profile
          echo 'eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"' >> /home/runner/.bash_profile
          eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
          brew tap homebrew/cask-fonts
          brew doctor --verbose